### ISSUE TITLE
add support for japanese

### ISSUE THREAD

**Issue by guilhermesilveira** [guilhermesilveira/generativemagic#16]
Implement support for japanese at https://github.com/guilhermesilveira/generativemagic/blob/main/generativemagic/spelling.py#L63

**Comment by misaka3** [comment]
Hi, I've done! https://github.com/guilhermesilveira/generativemagic/pull/17

**Comment by guilhermesilveira** [comment]
Thanks @misaka3 thats great! And fast.
- It looks like it make sense for us to go with エース instead of 一 , is it so?
- I've added a note regarding the の instead of `' of '`
- For the numbers we need to go hiragana on them. Because the card names are used for spelling when card counting it will be easier to use hiragana at first and then later refactor to support custom length support with kanjis

Can you make these small changes and push them again please?

**Comment by misaka3** [comment]
Hi, @guilhermesilveira .
I commited the change you said.

>It looks like it make sense for us to go with エース instead of 一 , is it so?

About this, I fixed '一' to 'えーす' instead of 'エース' because 'エース' is Katakana.
I made the following changes for the same reason.
・'じゃっく' instead of 'ジャック'
・'くいーん' instead of 'クイーン'
・'きんぐ' instead of 'キング'

**Comment by guilhermesilveira** [comment]
Thanks @misaka3 ! Merged

Sorry, I mentioned Hiragana but those words should be in Katakana, you were right, I accepted the pull request and made the change here:
https://github.com/guilhermesilveira/generativemagic/commit/135edd55ca6ff945d64b2b104ff749bfdd34d0f0

You can see I also changed the suit/value order (spadesのace, for instance)

Feel free to add support to other languages or ask me for something else you want to implement/explore
